#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, List, Tuple


ROOT_DIR = Path(__file__).resolve().parent
DATASETS_DIR = ROOT_DIR / "Datasets"
CONFIGS_DIR = ROOT_DIR / "configs"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate portable_runner dataset configs and launchers.")
    parser.add_argument("--datasets-dir", default=str(DATASETS_DIR))
    parser.add_argument("--configs-dir", default=str(CONFIGS_DIR))
    parser.add_argument("--overwrite", action="store_true")
    return parser.parse_args()


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def infer_jobs(datasets_dir: Path) -> List[Dict[str, str]]:
    jobs: List[Dict[str, str]] = []

    metaqa_root = datasets_dir / "MetaQA"
    if metaqa_root.exists():
        jobs.append(
            {
                "name": "metaqa",
                "dataset": "metaqa",
                "split": "test",
                "dataset_root": str(metaqa_root),
                "kb_path": str(metaqa_root / "kb.txt"),
                "relation_path": str(metaqa_root / "relations.json"),
                "extra": "METAQA_VARIANT=vanilla\nRUN_GRAMMAR=1\n",
            }
        )

    wikimovies_root = datasets_dir / "WikiMovies"
    if wikimovies_root.exists():
        jobs.append(
            {
                "name": "wikimovies",
                "dataset": "wikimovies",
                "split": "train",
                "dataset_root": str(wikimovies_root),
                "kb_path": str(wikimovies_root / "movieqa" / "knowledge_source" / "wiki_entities" / "wiki_entities_kb.txt"),
                "relation_path": "",
                "extra": "WIKIMOVIES_SUBSET=wiki_entities\nRUN_GRAMMAR=1\n",
            }
        )

    mlpq_root = datasets_dir / "MLPQ"
    if mlpq_root.exists():
        jobs.append(
            {
                "name": "mlpq_en_zh_en_ills",
                "dataset": "mlpq",
                "split": "test",
                "dataset_root": str(mlpq_root),
                "kb_path": str(
                    mlpq_root / "datasets" / "KGs" / "fusion_bilingual_KGs" / "ILLs_fusion" / "merged_ILLs_KG_en_zh.txt"
                ),
                "relation_path": "",
                "extra": "MLPQ_PAIR=en-zh\nMLPQ_QUESTION_LANG=en\nMLPQ_FUSION=ills\nRUN_GRAMMAR=1\n",
            }
        )

    normalized_jobs: List[Tuple[str, str, str]] = [
        ("WQSP", "wqsp", "test"),
        ("CWQ", "cwq", "test"),
        ("KQAPro", "kqapro", "test"),
        ("Mintaka", "mintaka", "test"),
    ]
    for dir_name, dataset_key, split in normalized_jobs:
        dataset_root = datasets_dir / dir_name
        normalized_file = dataset_root / "normalized" / f"{split}.jsonl"
        if normalized_file.exists():
            jobs.append(
                {
                    "name": dataset_key,
                    "dataset": dataset_key,
                    "split": split,
                    "dataset_root": str(dataset_root),
                    "dataset_file": str(normalized_file),
                    "kb_path": "/absolute/path/to/your/kb.txt",
                    "relation_path": "",
                    "extra": "RUN_GRAMMAR=1\n",
                }
            )

    return jobs


def maybe_comment_missing(path_str: str) -> str:
    path = Path(path_str)
    if not path_str:
        return ""
    return path_str if path.exists() else f"# missing locally: {path_str}"


def build_config_text(job: Dict[str, str]) -> str:
    lines = [
        "# Auto-generated by generate_configs.py",
        "PYTHON_BIN=",
        f"DATASET={job['dataset']}",
        f"SPLIT={job['split']}",
        f"KB_PATH={maybe_comment_missing(job['kb_path'])}",
    ]

    dataset_root = job.get("dataset_root", "")
    dataset_file = job.get("dataset_file", "")
    relation_path = job.get("relation_path", "")

    if dataset_root:
        lines.append(f"DATASET_ROOT={dataset_root}")
    else:
        lines.append("DATASET_ROOT=")

    if dataset_file:
        lines.append(f"DATASET_FILE={dataset_file}")
    else:
        lines.append("DATASET_FILE=")

    lines.extend(
        [
            "CUSTOM_DATASET_NAME=",
            "CUSTOM_FORMAT=jsonl",
            "CUSTOM_HOP=1",
            f"RELATION_PATH={maybe_comment_missing(relation_path) if relation_path else ''}",
            "GRAMMAR_PATH=",
            "RUN_GRAMMAR=1",
            "SAMPLE_LIMIT=100",
            "MODEL_FILTER=qwen2.5",
            "OUTPUT_FILE=",
            "DETAIL_CSV=",
        ]
    )

    extra = job.get("extra", "").strip()
    if extra:
        lines.append(extra)

    return "\n".join(lines).rstrip() + "\n"


def build_launcher_text(config_path: Path) -> str:
    return "\n".join(
        [
            "#!/usr/bin/env bash",
            "set -euo pipefail",
            'ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"',
            f'CONFIG_FILE="$ROOT_DIR/{config_path.relative_to(ROOT_DIR)}" bash "$ROOT_DIR/run_pipeline.sh"',
            "",
        ]
    )


def write_if_needed(path: Path, content: str, overwrite: bool) -> None:
    if path.exists() and not overwrite:
        return
    ensure_dir(path.parent)
    path.write_text(content, encoding="utf-8")


def main() -> int:
    args = parse_args()
    datasets_dir = Path(args.datasets_dir).resolve()
    configs_dir = Path(args.configs_dir).resolve()
    ensure_dir(configs_dir)

    jobs = infer_jobs(datasets_dir)
    for job in jobs:
        config_path = configs_dir / f"config.{job['name']}.env"
        launcher_path = configs_dir / f"run_{job['name']}.sh"
        write_if_needed(config_path, build_config_text(job), args.overwrite)
        write_if_needed(launcher_path, build_launcher_text(config_path), args.overwrite)
        launcher_path.chmod(0o755)
        print(f"[config] {config_path}")
        print(f"[launch] {launcher_path}")

    if not jobs:
        print("[config] no known datasets found under Datasets/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
